/* Salon × OpenKB — couche mémoire contextuelle (client).
 *
 * Voir docs/SALON-OPENKB.md (§9.3). Aucune dépendance ; n'agit que si un pont
 * est explicitement configuré (window.SALON_KB_CONFIG = { api: "..." }) ET
 * qu'un jeton Salon est présent. Sinon, le Salon garde son moteur déterministe
 * — ce fichier ne change rien.
 */
(function () {
  "use strict";
  var CFG = (typeof window !== "undefined" && window.SALON_KB_CONFIG) || {};
  function lang() {
    try { var s = localStorage.getItem("salon-locale"); if (s === "en" || s === "fr") return s; } catch (e) {}
    var l = (document.documentElement.getAttribute("lang") || "fr");
    return l.slice(0, 2) === "en" ? "en" : "fr";
  }
  function token() {
    try { return localStorage.getItem("kayros-salon-token") || ""; } catch (e) { return ""; }
  }
  function api() { return String(CFG.api || "").replace(/\/+$/, ""); }
  function enabled() { return Boolean(api() && token()); }

  function fetchJson(url, opts, ms) {
    var ctrl = typeof AbortController !== "undefined" ? new AbortController() : null;
    var timer = setTimeout(function () { try { ctrl && ctrl.abort(); } catch (e) {} }, ms || 6000);
    return fetch(url, Object.assign({}, opts, ctrl ? { signal: ctrl.signal } : {}))
      .then(function (r) { return r.json(); })
      .then(function (j) { clearTimeout(timer); return j; }, function (e) { clearTimeout(timer); throw e; });
  }

  function query(payload) {
    return fetchJson(api() + "/v1/salon/kb/query", {
      method: "POST",
      headers: { "content-type": "application/json", authorization: "Bearer " + token() },
      body: JSON.stringify(payload),
    }, 8000);
  }

  /** Passages ancrés par le pont (mêmes formes que le moteur) ou null. */
  function groundedPassages(authorId, question, context) {
    if (!enabled()) return Promise.resolve(null);
    return query({ authorId: authorId, question: question, context: context || {}, mode: "retrieval", k: 3 })
      .then(function (j) {
        if (!j || !j.ok || !j.passages || !j.passages.length) return null;
        var strong = j.passages.filter(function (p) { return !p.weak; });
        if (!strong.length) return null;
        return strong.map(function (p) {
          var s = p.sentence || p.s || "";
          return { id: p.id, w: p.work, work: p.work, text: s, sentence: s, s: s, score: p.score, src: p.src };
        });
      })
      .catch(function () { return null; });
  }

  var _manifest = null;
  function manifest() {
    if (_manifest) return Promise.resolve(_manifest);
    return fetch("kb-manifest.json", { cache: "no-cache" })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (j) { _manifest = j || null; return _manifest; })
      .catch(function () { return null; });
  }

  function paint() {
    var el = document.getElementById("kb-memory");
    if (!el) return;
    manifest().then(function (m) {
      if (!m || !m.totals) return;
      var t = m.totals;
      var fr = lang() === "fr";
      el.textContent = fr
        ? "Mémoire compilée · " + t.authors + " auteurs · " + t.sentences + " phrases · " + t.formulas + " formules"
        : "Compiled memory · " + t.authors + " authors · " + t.sentences + " sentences · " + t.formulas + " formulas";
      el.title = fr
        ? "Packs générés par le pipeline OpenKB — docs/SALON-OPENKB.md"
        : "Packs generated by the OpenKB pipeline — docs/SALON-OPENKB.md";
      el.hidden = false;
    });
  }

  var SalonKB = {
    version: "1.0.0",
    enabled: enabled,
    groundedPassages: groundedPassages,
    manifest: manifest,
    paint: paint,
  };
  if (typeof window !== "undefined") window.SalonKB = SalonKB;
  if (typeof document !== "undefined") {
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", paint);
    else paint();
    /* La bascule de langue du Salon recharge ses textes : la mémoire suit, sans mélange. */
    document.addEventListener("click", function (e) {
      var el = e && e.target;
      var inLang = false;
      while (el && el !== document) {
        if (el.className && String(el.className).split(/\s+/).indexOf("lang") !== -1) { inLang = true; break; }
        el = el.parentNode;
      }
      if (inLang) setTimeout(paint, 80);
    });
  }
})();
