import { useI18n } from '../i18n/I18nContext.jsx';
import { ENTITY_TYPES } from '../data/ontology.js';

export default function PdfExport({ idea, competitors, baseline, ki, gaps }) {
  const { t } = useI18n();

  if (!competitors || competitors.length === 0) return null;

  const handlePrint = () => window.print();

  const allScores = ENTITY_TYPES.map((et) => {
    const ours = baseline?.[et.id] ?? null;
    const compScores = competitors.map((c) => c.scores?.[et.id] ?? null).filter((v) => v !== null);
    const avg = compScores.length > 0 ? Math.round(compScores.reduce((a, b) => a + b, 0) / compScores.length) : null;
    return { entity: et, ours, avg, diff: ours !== null && avg !== null ? ours - avg : null };
  });

  return (
    <>
      <div className="export-bar">
        <button className="btn btn-primary" onClick={handlePrint}>
          🖨️ Print / PDF
        </button>
      </div>

      <div className="print-report">
        <div className="print-header">
          <h1>KayrosLab — Analysis Report</h1>
          <p className="print-date">{new Date().toLocaleDateString()}</p>
        </div>

        <section className="print-section">
          <h2>Idea</h2>
          <p className="print-idea">{idea}</p>
        </section>

        {ki !== null && (
          <section className="print-section">
            <h2>Kayros Index</h2>
            <div className="print-ki">{ki}/100</div>
          </section>
        )}

        <section className="print-section">
          <h2>Competitors</h2>
          <table className="print-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Score</th>
                {ENTITY_TYPES.map((et) => <th key={et.id}>{et.name}</th>)}
              </tr>
            </thead>
            <tbody>
              {competitors.map((c) => (
                <tr key={c.name}>
                  <td>{c.name}</td>
                  <td className="print-num">{c.avgScore}</td>
                  {ENTITY_TYPES.map((et) => <td key={et.id} className="print-num">{c.scores?.[et.id] ?? '—'}</td>)}
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {gaps && gaps.length > 0 && (
          <section className="print-section">
            <h2>Gap Analysis</h2>
            <table className="print-table">
              <thead>
                <tr><th>Dimension</th><th>Diff</th><th>Status</th></tr>
              </thead>
              <tbody>
                {gaps.map((g, i) => (
                  <tr key={i}>
                    <td>{g.icon} {g.entityName || g.neuronId}</td>
                    <td className="print-num">{g.diff > 0 ? '+' : ''}{g.diff}</td>
                    <td>{g.type === 'advantage' ? 'Advantage' : 'Disadvantage'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        <section className="print-section">
          <h2>Ontology Dimensions</h2>
          <div className="print-dimensions">
            {ENTITY_TYPES.map((et) => (
              <div key={et.id} className="print-dim">
                <span className="print-dim-icon">{et.icon}</span>
                <div>
                  <strong>{et.name}</strong>
                  <span className="print-dim-desc">{et.description}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        <div className="print-footer">
          Generated by KayrosLab — {new Date().toISOString()}
        </div>
      </div>
    </>
  );
}
