function buildFallbackExplorationCandidates(round, reason){
  const lang=cycleLanguage();
  const idea=demoState.originalIdea||'';
  const base=idea.slice(0,160);
  if(lang==='en'){
    return [
      normalizeIdeaCandidate({ title:'Clarify the beneficiary', reframedIdea:'Rephrase around one primary beneficiary: who gains what from "'+base+'"?', kayrosSignature:'Ambiguity on the beneficiary blocks ranking.', opening:'A named beneficiary unlocks relevance and testability.', shiftedAssumption:'We assumed the audience was already obvious.', falsifiableHypothesis:'If we cannot name one primary beneficiary in one sentence, the idea is still multi-interpreted.', firstExperiment:'Write: For [persona], this solves [pain] by [mechanism]. Then regenerate.', signals:['One named persona','One quantified pain'], criticalUnknowns:['Primary beneficiary?','What pain is acute enough to change behavior?'], rationale:'Advance by narrowing who it is for.', scores:{novelty:4,relevance:8,testability:8} },0,round),
      normalizeIdeaCandidate({ title:'Stress the non-negotiable constraint', reframedIdea:'Restate the idea under one hard constraint (budget, regulation, time, sovereignty).', kayrosSignature:'Constraints create distinctive options.', opening:'A hard constraint forces divergent challengers.', shiftedAssumption:'Constraints were optional footnotes.', falsifiableHypothesis:'If no constraint changes the idea shape, we are still in generic ideation.', firstExperiment:'Pick one constraint and rewrite the idea in 2 lines under it.', signals:['Constraint named','Idea shape changed'], criticalUnknowns:['Which constraint is non-negotiable?','What must we drop?'], rationale:'Progress via constraint.', scores:{novelty:6,relevance:7,testability:7} },1,round),
      normalizeIdeaCandidate({ title:'Define a 90-day success signal', reframedIdea:'Turn the idea into a hypothesis with a 90-day observable success signal for "'+base+'".', kayrosSignature:'Without a success signal, novelty cannot be ranked.', opening:'A measurable signal unlocks later stress-testing.', shiftedAssumption:'Success was left unbounded.', falsifiableHypothesis:'If we cannot state one observable signal at D+90, the idea is not decision-ready.', firstExperiment:'Write: At D+90 we will observe [signal] on [population]. Then relaunch.', signals:['One metric','Defined population'], criticalUnknowns:['What is the D+90 signal?','What forces a no-go?'], rationale:'Keep the loop moving with a testable framing.', scores:{novelty:5,relevance:7,testability:9} },2,round)
    ];
  }
  return [
    normalizeIdeaCandidate({ title:'Clarifier le beneficiaire', reframedIdea:'Reformuler autour d un seul beneficiaire principal : qui gagne quoi avec "'+base+'" ?', kayrosSignature:'L ambiguite sur le beneficiaire bloque le ranking.', opening:'Un beneficiaire nomme debloque pertinence et testabilite.', shiftedAssumption:'On a suppose que la cible etait evidente.', falsifiableHypothesis:'Si on ne peut pas nommer un beneficiaire principal en une phrase, l idee reste multi-interpretable.', firstExperiment:'Ecrire : Pour [persona], cela resout [douleur] via [mecanisme]. Puis regenerer.', signals:['Une persona nommee','Une douleur quantifiee'], criticalUnknowns:['Beneficiaire principal ?','Quelle douleur est assez aigue ?'], rationale:'Avancer en resserrant le pour-qui.', scores:{novelty:4,relevance:8,testability:8} },0,round),
    normalizeIdeaCandidate({ title:'Forcer une contrainte non negociable', reframedIdea:'Reformuler l idee sous une contrainte dure (budget, regulation, delai, souverainete).', kayrosSignature:'Les contraintes creent des options distinctives.', opening:'Une contrainte dure force des variantes divergentes.', shiftedAssumption:'Les contraintes etaient optionnelles.', falsifiableHypothesis:'Si aucune contrainte ne change la forme de l idee, on reste generique.', firstExperiment:'Choisir une contrainte et reecrire l idee en 2 lignes sous cette contrainte.', signals:['Contrainte nommee','Forme modifiee'], criticalUnknowns:['Quelle contrainte est non negociable ?','Que faut-il abandonner ?'], rationale:'Progresser par la contrainte.', scores:{novelty:6,relevance:7,testability:7} },1,round),
    normalizeIdeaCandidate({ title:'Definir un signal de succes a 90 jours', reframedIdea:'Transformer l idee en hypothese avec un signal observable a 90 jours pour "'+base+'".', kayrosSignature:'Sans signal de succes, la nouveaute ne peut pas etre rankee.', opening:'Un signal mesurable permet la suite du cycle.', shiftedAssumption:'Le succes etait non borne.', falsifiableHypothesis:'Si on ne peut pas enoncer un signal a J+90, l idee n est pas arbitrable.', firstExperiment:'Ecrire : A J+90 nous observerons [signal] sur [population]. Puis relancer.', signals:['Une metrique','Population definie'], criticalUnknowns:['Quel signal a J+90 ?','Qu est-ce qui impose un no-go ?'], rationale:'Faire avancer la boucle avec un cadrage testable.', scores:{novelty:5,relevance:7,testability:9} },2,round)
  ];
}
