import { computeKI, forecastSeries } from "./engine";
import type { Workspace } from "./types";

const now = "2026-08-28T09:00:00.000Z";

const kiOracle = computeKI({
  global: 8.2,
  velocite: 7.1,
  divergence: 8.6,
  fiabilite: 7.8,
  impact: 8.4,
  originalite: 9.1,
});
const kiPos = computeKI({
  global: 7.4,
  velocite: 6.8,
  divergence: 7.9,
  fiabilite: 7.2,
  impact: 7.0,
  originalite: 8.0,
});
const kiFile = computeKI({
  global: 6.1,
  velocite: 5.4,
  divergence: 8.8,
  fiabilite: 8.1,
  impact: 6.4,
  originalite: 8.5,
});
const kiConsole = computeKI({
  global: 8.8,
  velocite: 7.6,
  divergence: 7.4,
  fiabilite: 8.0,
  impact: 9.0,
  originalite: 8.2,
});

const hist = [12, 14, 13, 16, 18, 19, 21, 20, 23, 25, 24, 28, 30, 29, 33, 36, 35, 39, 42, 44];

export const SEED: Workspace = {
  tenantName: "KayrosLab · atelier gouverné",
  locale: "fr",
  view: "board",
  selectedIdeaId: "idea-oracle",
  selectedAgentId: null,
  selectedGateId: null,
  selectedFactId: null,
  inspectorOpen: true,
  editEverything: true,
  guideDismissed: false,
  steps: [
    { id: "recueillir", n: "00", fr: "Recueillir", en: "Intake", roleFr: "Canevas d'entrée comparable", roleEn: "Structured intake canvas", outputFr: "Idée comparable", outputEn: "Comparable idea", agentId: "planner", enabled: true, durationMs: 520 },
    { id: "ecouter", n: "01", fr: "Écouter", en: "Listen", roleFr: "Réduction de bruit, scoring, clusters", roleEn: "Noise reduction, scoring, clusters", outputFr: "Signaux qualifiés", outputEn: "Qualified signals", agentId: "scanner", enabled: true, durationMs: 640 },
    { id: "cartographier", n: "02", fr: "Cartographier", en: "Map", roleFr: "Réseau de tendances et ponts", roleEn: "Trend network and bridges", outputFr: "Graphe + ponts", outputEn: "Graph + bridges", agentId: "mapper", enabled: true, durationMs: 700 },
    { id: "construire", n: "03", fr: "Construire", en: "Build", roleFr: "Scénarios, collisions, brief", roleEn: "Scenarios, collisions, brief", outputFr: "Scénarios + hypothèses", outputEn: "Scenarios + hypotheses", agentId: "bisociator", enabled: true, durationMs: 860 },
    { id: "positionner", n: "04", fr: "Positionner", en: "Position", roleFr: "Veille web / GitHub / ArXiv → L1", roleEn: "Web / GitHub / ArXiv scan → L1", outputFr: "Ontologie + faits concurrent", outputEn: "Ontology + competitor facts", agentId: "positioner", enabled: true, durationMs: 780 },
    { id: "eprouver", n: "05", fr: "Éprouver", en: "Challenge", roleFr: "Critic, Devil's Advocate, Red Team", roleEn: "Critic, Devil's Advocate, Red Team", outputFr: "Rapport d'attaque", outputEn: "Attack report", agentId: "redteam", enabled: true, durationMs: 720 },
    { id: "arbitrer", n: "06", fr: "Arbitrer", en: "Decide", roleFr: "Vote pondéré, porte, veto", roleEn: "Weighted vote, gate, veto", outputFr: "Go / No-Go / Révision", outputEn: "Go / No-Go / Revise", agentId: "synthesizer", enabled: true, durationMs: 640 },
    { id: "projeter", n: "07", fr: "Projeter", en: "Project", roleFr: "Trajectoire, ressources, foresight", roleEn: "Trajectory, resources, foresight", outputFr: "Roadmap + boucle KPI", outputEn: "Roadmap + KPI loop", agentId: "projection", enabled: true, durationMs: 700 },
    { id: "realiser", n: "08", fr: "Réaliser", en: "Execute", roleFr: "Pilote → déploiement → bilan", roleEn: "Pilot → deploy → review", outputFr: "Jalons + impact mesuré", outputEn: "Milestones + measured impact", agentId: "tracker", enabled: true, durationMs: 820 },
  ],
  ideas: [
    {
      id: "idea-oracle",
      title: "Sales Oracle pour comités d'achat industriels",
      brief: "Révéler les chemins de veto, objections et conditions de GO avant d'envoyer une proposition énergie / souveraineté.",
      constraints: ["Labelliser toute simulation", "Arbitrage humain obligatoire", "Pas de scraping LinkedIn"],
      category: "oracle",
      author: "Comex",
      stage: "construire",
      status: "en_revue",
      ki: kiOracle,
      signals: [],
      collisions: [],
      ontology: { nodes: [], edges: [] },
      attacks: [],
      votes: [],
      roadmap: [],
      forecast: forecastSeries(hist, 8, 11),
      kpis: [
        { name: "KI stratégique", target: 7.5, actual: kiOracle.global, unit: "/10" },
        { name: "Cycles arbitrés", target: 12, actual: 4, unit: "n" },
      ],
      dormant: false,
      createdAt: now,
      updatedAt: now,
      history: [{ ts: now, type: "created", detail: "Intake structuré" }],
    },
    {
      id: "idea-positioner",
      title: "Positioner ontologique GitHub / ArXiv",
      brief: "Scanner le paysage, exporter OWL, injecter les concurrents en faits L1.",
      constraints: ["Sources citées", "Graphe inspectable"],
      category: "positioner",
      author: "Recherche",
      stage: "cartographier",
      status: "en_developpement",
      ki: kiPos,
      signals: [],
      collisions: [],
      ontology: { nodes: [], edges: [] },
      attacks: [],
      votes: [],
      roadmap: [],
      forecast: forecastSeries(hist.map((n) => n * 0.7), 8, 3),
      kpis: [{ name: "Nœuds ontologie", target: 80, actual: 36, unit: "n" }],
      dormant: false,
      createdAt: now,
      updatedAt: now,
      history: [{ ts: now, type: "created", detail: "Veille démarrée" }],
    },
    {
      id: "idea-filenymous",
      title: "Intake confidentiel pair-à-pair",
      brief: "Déposer un brief chiffré localement avant tout partage d'atelier.",
      constraints: ["Chiffrement local", "Pas de compte central"],
      category: "privacy",
      author: "Sécu",
      stage: "eprouver",
      status: "en_pause",
      ki: kiFile,
      signals: [],
      collisions: [],
      ontology: { nodes: [], edges: [] },
      attacks: [],
      votes: [],
      roadmap: [],
      forecast: forecastSeries(hist.map((n) => n * 0.4 + 8), 8, 19),
      kpis: [{ name: "Confiance", target: 9, actual: 8.1, unit: "/10" }],
      dormant: true,
      createdAt: now,
      updatedAt: now,
      history: [{ ts: now, type: "status", detail: "Mise en pause capitalisation" }],
    },
    {
      id: "idea-console",
      title: "Console-matrice — poste unique KayrosLab",
      brief: "Une matrice de travail où chaque feature est opérante, éditable, visualisable, mesurable.",
      constraints: ["Tout est éditable", "Ludique", "Jusqu'au résultat mesuré"],
      category: "console",
      author: "Produit",
      stage: "recueillir",
      status: "nouveau",
      ki: kiConsole,
      signals: [],
      collisions: [],
      ontology: { nodes: [], edges: [] },
      attacks: [],
      votes: [],
      roadmap: [],
      forecast: forecastSeries(hist.map((n) => n * 0.9 + 4), 8, 7),
      kpis: [{ name: "Features opérantes", target: 17, actual: 17, unit: "n" }],
      dormant: false,
      createdAt: now,
      updatedAt: now,
      history: [{ ts: now, type: "created", detail: "Canevas console" }],
    },
  ],
  agents: [
    { id: "planner", displayName: "Planner", role: "Cadrage", department: "Stratégie", seniority: "senior", mission: "Transformer un signal faible en plan exécutable.", instructions: "Objectifs, contraintes, rôles, plan.", constraints: ["Ne pas inventer de faits"], rules: ["Le plan cite les permissions"], tools: ["intake"], connectors: ["console"], provider: "ollama", model: "llama3.1:8b-instruct", quant: "q4_K_M", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "scanner", displayName: "Signal Scanner", role: "Écoute", department: "Insight", seniority: "senior", mission: "Qualifier le bruit en signaux pondérés.", instructions: "Cluster, score, sources.", constraints: [], rules: ["Toute source est citée"], tools: ["cluster"], connectors: ["console"], provider: "ollama", model: "llama3.1:8b-instruct", quant: "q4_K_M", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "mapper", displayName: "Trend Mapper", role: "Cartographe", department: "Insight", seniority: "senior", mission: "Relier tendances et ponts bisociatifs.", instructions: "", constraints: [], rules: [], tools: ["graph"], connectors: ["console"], provider: "ollama", model: "llama3.1:8b-instruct", quant: "q4_K_M", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "bisociator", displayName: "Bisociateur", role: "Collision", department: "Idéation", seniority: "senior", mission: "Produire des collisions Framework × Mécanisme × Pont.", instructions: "Chaque candidat porte une Kayros Signature.", constraints: [], rules: ["Filtrer les quasi-doublons > 0.82"], tools: ["novelty"], connectors: ["console"], provider: "ollama", model: "qwen2.5:14b", quant: "q5_K_M", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "positioner", displayName: "Positioner", role: "Veille", department: "Recherche", seniority: "senior", mission: "Scanner web, GitHub, GitLab, ArXiv et injecter L1.", instructions: "", constraints: ["Pas de scraping illicite"], rules: ["Faits concurrent → L1"], tools: ["github", "arxiv"], connectors: ["console"], provider: "mistral", model: "mistral-small", quant: "", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "critic", displayName: "Critic", role: "Critique", department: "Risque", seniority: "senior", mission: "Attaquer les claims et la faisabilité.", instructions: "", constraints: [], rules: [], tools: ["challenge"], connectors: ["console"], provider: "ollama", model: "llama3.1:8b-instruct", quant: "q4_K_M", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "redteam", displayName: "Red Team", role: "Attaque", department: "Risque", seniority: "executive", mission: "Casser le dossier avant le comité réel.", instructions: "", constraints: [], rules: ["Le veto n'est jamais silencieux"], tools: ["challenge"], connectors: ["console"], provider: "ollama", model: "llama3.1:70b", quant: "q5_K_M", enabled: true, vetoPower: true, kind: "system", consent: false },
    { id: "synthesizer", displayName: "Synthesizer", role: "Arbitre", department: "Gouvernance", seniority: "executive", mission: "Agréger sans écraser le veto.", instructions: "Vote instruit, veto décide.", constraints: [], rules: ["Porte humaine obligatoire si sensible"], tools: ["gate"], connectors: ["console", "slack"], provider: "claude", model: "opus", quant: "", enabled: true, vetoPower: true, kind: "system", consent: false },
    { id: "cfo", displayName: "CFO simulé", role: "Finance", department: "Finance", seniority: "executive", mission: "Juger viabilité et preuves chiffrées.", instructions: "DISC C, déclencheur: ROI 18 mois.", constraints: ["Profil consenti uniquement"], rules: ["NO_GO si le business case est non sourcé"], tools: ["oracle"], connectors: ["console"], provider: "ollama", model: "llama3.1:8b-instruct", quant: "q4_K_M", enabled: true, vetoPower: true, kind: "hybrid", consent: true, personality: { source: "structured", provenance: "Export structuré autorisé · 2026-08-12", disc: "C", notes: "Veut des preuves, pas des récits." } },
    { id: "projection", displayName: "Projection", role: "Foresight", department: "Ops", seniority: "senior", mission: "Trajectoire déterministe + option TimesFM.", instructions: "Toujours labelliser SIMULATION.", constraints: [], rules: [], tools: ["timesfm"], connectors: ["console"], provider: "ollama", model: "llama3.1:8b-instruct", quant: "q4_K_M", enabled: true, vetoPower: false, kind: "system", consent: false },
    { id: "tracker", displayName: "Execution Tracker", role: "Suivi", department: "Ops", seniority: "senior", mission: "Pilote, déploiement, bilan, dérive KPI.", instructions: "", constraints: [], rules: ["Le KPI observé nourrit Écouter"], tools: ["kpi"], connectors: ["console", "slack"], provider: "mock", model: "mock", quant: "", enabled: true, vetoPower: false, kind: "system", consent: false },
  ],
  swarms: [
    {
      id: "swarm-comex",
      name: "Comex interne",
      agentIds: ["cfo", "redteam", "synthesizer", "planner"],
      purpose: "Révéler le veto path avant un GO interne.",
      votingThreshold: "veto_power_csuite",
      personalityEnabled: true,
    },
    {
      id: "swarm-cycle",
      name: "Cycle stratégique 8",
      agentIds: ["planner", "scanner", "mapper", "bisociator", "positioner", "critic", "redteam", "synthesizer"],
      purpose: "Parcours complet Intake → Decide. Projection et Execute restent hors essaim.",
      votingThreshold: "majority",
      personalityEnabled: false,
    },
    {
      id: "swarm-ops",
      name: "Boucle KPI",
      agentIds: ["projection", "tracker"],
      purpose: "Projeter puis réaliser — le KPI observé nourrit Écouter.",
      votingThreshold: "majority",
      personalityEnabled: false,
    },
  ],
  memory: [
    { id: "m-l0-1", layer: "L0", text: "Canevas actif : Sales Oracle énergie industrielle.", source: "working", ideaId: "idea-oracle", createdAt: now },
    { id: "m-l1-1", layer: "L1", text: "Brightidea n'orchestre pas d'essaim à veto explicite.", source: "positioner", ideaId: "idea-positioner", createdAt: now },
    { id: "m-l1-2", layer: "L1", text: "Wazoku score l'idéation, pas la nouveauté par embeddings.", source: "positioner", createdAt: now },
    { id: "m-l2-1", layer: "L2", text: "Scénario A : GO conditionnel si le corpus cite 3 veto holders.", source: "distill", ideaId: "idea-oracle", createdAt: now },
    { id: "m-l3-1", layer: "L3", text: "Norme tenant : vote instruit, veto décide, SIMULATION labellisée.", source: "persona", createdAt: now },
  ],
  gates: [
    {
      id: "gate-oracle",
      ideaId: "idea-oracle",
      status: "open",
      openedAt: now,
      votes: [
        { agentId: "cfo", weight: 2, verdict: "CONDITIONAL_GO", reason: "ROI sourcé à 18 mois, sinon NO_GO." },
        { agentId: "redteam", weight: 2, verdict: "NO_GO", reason: "Le corpus ne cite pas le veto sécurité." },
        { agentId: "synthesizer", weight: 2, verdict: "CONDITIONAL_GO", reason: "GO si les 3 veto holders sont cités." },
      ],
    },
  ],
  connectors: [
    { platform: "slack", status: "connected", enabled: true, rooms: 2, fields: { signing: "••••", bot: "••••" }, webhook: "https://api.kayroslab.com/v1/connectors/slack/configured/demo", lastTest: now },
    { platform: "teams", status: "configured", enabled: true, rooms: 1, fields: { appId: "azure-bot-demo" }, webhook: "https://api.kayroslab.com/v1/connectors/teams/configured/demo" },
    { platform: "discord", status: "missing", enabled: false, rooms: 0, fields: {}, webhook: "" },
  ],
  mcpTools: [
    { id: "cycle.run", name: "cycle.run", scope: "cycle:write", description: "Lancer un cycle gouverné, tenant-scopé.", enabled: true },
    { id: "gates.resolve", name: "gates.resolve", scope: "gov:write", description: "Résoudre une porte approve/reject/revise.", enabled: true },
    { id: "memory.promote", name: "memory.promote", scope: "memory:write", description: "Promouvoir L0→L1→L2→L3.", enabled: true },
    { id: "swarm.run", name: "swarm.run", scope: "swarm:write", description: "Exécuter un essaim avec veto.", enabled: true },
    { id: "oracle.rehearse", name: "oracle.rehearse", scope: "oracle:write", description: "Simuler un comité, labellisé SIMULATION.", enabled: true },
    { id: "forecast.kpi", name: "forecast.kpi", scope: "forecast:read", description: "Bandes P10–P90 TimesFM.", enabled: true },
  ],
  oracleCases: [
    {
      id: "socase-rfp",
      name: "RFP datacenter souverain",
      useCase: "rfp",
      question: "Peut-on envoyer l'offre ce vendredi au comité sécurité + finance ?",
      committee: [
        { agentId: "cfo", veto: true },
        { agentId: "redteam", veto: true },
        { agentId: "synthesizer", veto: false },
      ],
      evidence: ["RFP.pdf", "Annexe sécurité.md", "Business case.csv"],
    },
  ],
  cycle: null,
  kiWeights: {
    fitStrategique: { global: 0.5, impact: 0.5 },
    desirabilite: { impact: 0.6, originalite: 0.4 },
    faisabilite: { fiabilite: 0.7, velocite: 0.3 },
    viabilite: { global: 0.4, fiabilite: 0.6 },
    adaptabilite: { divergence: 0.5, originalite: 0.5 },
  },
  flags: {
    sseLive: true,
    layeredMemory: true,
    noveltyEngine: true,
    kayrosSignature: true,
    positioner: true,
    quantLlm: true,
    specializedSwarms: true,
    personality: true,
    salesOracle: true,
    mcpPortal: true,
    chatConnectors: true,
    portfolioUx: true,
    timesfm: true,
    adaptersV16: true,
  },
  specs: [],
  adapters: [
    { id: "langchain", name: "LangChain tools bridge", enabled: false, note: "Périphérie. Le core reste zero-dep." },
    { id: "langgraph", name: "LangGraph research runner", enabled: false, note: "Sous-graphe gather → synthesize." },
    { id: "search", name: "Search tools multi-provider", enabled: true, note: "Tavily / Brave / Google / DDG." },
    { id: "langfuse", name: "Langfuse observability", enabled: false, note: "Spans LLM + tools, no-op si clés absentes." },
  ],
};
